actors:
  takasy:
    image_url: /images/actors/takasy.png
    name: takasy
    url: https://twitter.com/takattata
  tomoya0x00:
    image_url: /images/actors/tomoya0x00.jpg
    name: tomoya0x00
    url: https://twitter.com/tomoya0x00
  nkano_t:
    image_url: /images/actors/nkano_t.jpg
    name: nkano_t
    url: https://twitter.com/nkano_t
author: takasy
description: 知り合ったソフトウェアエンジニアたちの今までやこれからを聞いていくpodcast
description_long: アプリエンジニアをしているtakasyがゲストのエンジニア人生をお聞きしていくpodcastです。ご意見ご要望、出演希望などありましたら<a href=https://twitter.com/deploy_fm>@deploy_fm</a>にメンションください。
email: 
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-126251433-1
hashtag: deployfm
itunes_podcast_url:
keywords: deployfm
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: deploy.fm
url: https://takattata.github.io/deployfm/
